
services:
  #* Docentes: Bases de datos y servicio
  docentes-db:    
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_DOCENTES}    
    ports: 
      - "5433:5432"
    volumes: 
      - docentes_data:/var/lib/postgresql/data

  docentes-service:
    build: ./docentes-service
    container_name: docentes_service
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_DOCENTES}
      DB_HOST: docentes-db
      DB_PORT: ${DB_PORT}    
    ports:
      - "5001:5001"
    depends_on: 
      - docentes-db

  #* Cursos: Bases de datos y servicio
  cursos-db:    
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_CURSOS}
    ports:
      - "5434:5432"
    volumes: 
      - cursos_data:/var/lib/postgresql/data

  cursos-service:
    build: ./cursos-service
    container_name: cursos_service
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_CURSOS}
      DB_HOST: cursos-db
      DB_PORT: ${DB_PORT}    
    ports:
      - "5002:5002"
    depends_on: 
      - cursos-db

  #* Estudiantes: Bases de datos y servicio
  estudiantes-db:    
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_ESTUDIANTES}
    ports:
      - "5435:5432"
    volumes: 
      - estudiantes_data:/var/lib/postgresql/data

  estudiantes-service:
    build: ./estudiantes-service
    container_name: estudiantes_service
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_ESTUDIANTES}
      DB_HOST: estudiantes-db
      DB_PORT: ${DB_PORT}    
    ports:
      - "5003:5003"
    depends_on: 
      - estudiantes-db

  #* Matriculas: Bases de datos y servicio
  matriculas-db:    
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_MATRICULAS}
    ports:
      - "5436:5432"
    volumes: 
      - matriculas_data:/var/lib/postgresql/data

  matriculas-service:
    build: ./matriculas-service
    container_name: matriculas_service
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_MATRICULAS}
      DB_HOST: matriculas-db
      DB_PORT: ${DB_PORT}    
    ports:
      - "5004:5004"
    depends_on: 
      - matriculas-db

  #* Notas: Bases de datos y servicio
  notas-db:    
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_NOTAS}    
    ports:
      - "5437:5432"
    volumes: 
      - notas_data:/var/lib/postgresql/data

  notas-service:
    build: ./notas-service
    container_name: notas_service
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_NOTAS}
      DB_HOST: notas-db
      DB_PORT: ${DB_PORT}    
    ports:
      - "5005:5005"
    depends_on: 
      - notas-db
  
  gateway:
    build: ./gateway
    container_name: api_gateway
    ports:
      - "8000:80"
    volumes:
      - ./fronentd:/usr/share/nginx/html
    depends_on:
      - docentes-service
      - cursos-service
      - estudiantes-service
      - matriculas-service
      - notas-service

#* Volumenes globales, Docentes:
volumes: 
  docentes_data:
  cursos_data:
  estudiantes_data:
  matriculas_data:
  notas_data: