events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Aqui mostramos el home
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Redirección a Docentes
        location /docentes {
            proxy_pass http://docentes-service:5001/docentes;
        }

        # Redirección a Cursos
        location /cursos {
            proxy_pass http://cursos-service:5002/cursos;
        }

        # Redirección a Estudiantes
        location /estudiantes {
            proxy_pass http://estudiantes-service:5003/estudiantes;
        }

        # Redirección a Matrículas
        location /matriculas {
            proxy_pass http://matriculas-service:5004/matriculas;
        }

        # Redirección a Notas
        location /notas {
            proxy_pass http://notas-service:5005/notas;
        }
    }
}