events {
    worker_connections 1024;
}

http {
    server {
        listen 80;


        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /docentes {
            proxy_pass http://docentes-service:5001/docentes;
        }

        location /cursos {
            proxy_pass http://cursos-service:5002/cursos;
        }

        location /estudiantes {
            proxy_pass http://estudiantes-service:5003/estudiantes;
        }

        location /matriculas {
            proxy_pass http://matriculas-service:5004/matriculas;
        }

        location /notas {
            proxy_pass http://notas-service:5005/notas;
        }
    }
}