events {
    worker_connections 1024;
}

http {
    # DNS interno de Docker para no cachear IPs viejas de los servicios
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;

        # Aqui mostramos el home
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Redirección a Docentes
        location /docentes {
            set $docentes_upstream docentes-service;
            proxy_pass http://$docentes_upstream:5001;
        }

        # Redirección a Cursos
        location /cursos {
            set $cursos_upstream cursos-service;
            proxy_pass http://$cursos_upstream:5002;
        }

        # Redirección a Estudiantes
        location /estudiantes {
            set $estudiantes_upstream estudiantes-service;
            proxy_pass http://$estudiantes_upstream:5003;
        }

        # Redirección a Matrículas
        location /matriculas {
            set $matriculas_upstream matriculas-service;
            proxy_pass http://$matriculas_upstream:5004;
        }

        # Redirección a Notas
        location /notas {
            set $notas_upstream notas-service;
            proxy_pass http://$notas_upstream:5005;
        }
    }
}
